### ISSUE TITLE
Add Damage Indicator to the Stats

### ISSUE THREAD

**Issue by mexikoedi** [TTT-2/ttt2-weaponstats#1]
A damage Indicator is really helpful especially for new players. Here is an example: https://steamcommunity.com/sharedfiles/filedetails/?id=300375321 .

**Comment by TimGoll** [comment]
yes, will be done as soon as I have time! :)

**Comment by mexikoedi** [comment]
No stress, only wanted to report it here on GitHub, its more organized here. Thanks.

**Comment by TimGoll** [comment]
done! :)

![image](https://user-images.githubusercontent.com/13639408/75725037-efde3100-5cdf-11ea-95d0-b3e6ea461e21.png)
