### ISSUE TITLE
Bug: Doesn't show stats if weapons spawned later in a round

### ISSUE THREAD

**Issue by mexikoedi** [TTT-2/ttt2-weaponstats#7]
The stats aren't working correctly after newest TTT2 Base update(s) (November.2021).
For example on the map "ttt_lttp_kakariko_a5" the stats are only seen after picking up the weapon and dropping it.

(This was commented on the steam workshop page.)

**Comment by ZenBre4ker** [comment]
What stats? TTT2 doesnt have stats, do you mean the weapon stats addon?

**Comment by mexikoedi** [comment]
> What stats? TTT2 doesnt have stats, do you mean the weapon stats addon?

Yes, isn't this the weapon stats repo?

**Comment by ZenBre4ker** [comment]
oops, Im sry, didnt see that.

**Comment by ZenBre4ker** [comment]
Okay, I can validate it for kakariko. Not sure yet, but it seems like those weapons spawn without that data.

**Comment by ZenBre4ker** [comment]
But it was also before latest patch. I tested before the spawneditor and that works.
https://github.com/TTT-2/TTT2/commit/023e3f17459c96bc8b0e5f15871aec2019245fd0

And with the spawneditor and the kakariko patch:
https://github.com/TTT-2/TTT2/commit/aa789336d01d6ad06c457ef9cdafbca092dd7551

Inbetween cant be tested as we fixed triggered spawns only in the latter.
So it probably has to do with that 🤔

**Comment by mexikoedi** [comment]
Yeah, I just saw the comment on steam and the answer of Tim. So I posted this issue.

Are there no stats at all shown or only specific parts?

**Comment by TimGoll** [comment]
I have a suspicion. And I bet it has been this way since forever

**Comment by mexikoedi** [comment]
Is the issue maybe here somewhere: https://github.com/TTT-2/TTT2/commit/f6f9b0b8a1441593bc342499675e3c38ff80fd7f#diff-d988fe03725c51db40a282655ea00c1efbba424378f6802af36ae48c0a4a800cR48 ?

For example is this correct: https://github.com/TTT-2/TTT2/commit/f6f9b0b8a1441593bc342499675e3c38ff80fd7f#diff-d988fe03725c51db40a282655ea00c1efbba424378f6802af36ae48c0a4a800cR91 ? What does "entData.t" do? Don't know exactly and I'm on mobile so it's a bit hard to look into it.
 
(It is opening the line in google for me. Is this viewable?)

**Comment by ZenBre4ker** [comment]
Nah, its not regularly spawned, but force spawned here
https://github.com/TTT-2/TTT2/commit/aa789336d01d6ad06c457ef9cdafbca092dd7551#diff-16157c7782182f721199f1ad2d1feae7ae898456af1461db76e987e48b6d75d9R58

So the error should lie here:
https://github.com/TTT-2/TTT2/blob/master/lua/ttt2/libraries/entspawn.lua#L137

The Clip1() of the weapon is not intialized on the client. So either it is not synced or just not initialized.
